### ISSUE TITLE
Confusion about model fit statistic

### ISSUE THREAD

**Issue by mwaskom** [kendrickkay/analyzePRF#1]
Hi Kendrick,

I'm getting some confusing results when using analyzePRF; I'm hoping you can help me debug.

I'm analyzing standard bars data (with checkerboards in the aperture). Here is a plot of what the R2 statistic as reported by analyzePRF looks like in visual cortex:

![screenshot 2016-01-28 17 21 37](https://cloud.githubusercontent.com/assets/315810/12664351/ac26b35c-c5e3-11e5-8e9f-860a96142c73.png)

As you can see, some aspects of it look right, but other aspects of it look like swiss cheese.

There's nothing apparently wrong in the mean maps, and actually these data have been processed in mrVista (not by me) and everything looks good there. Things looks pretty OK in analyzePRF too, if I use separate runs with raw signal units, but here I'm trying to compare more directly to mrVista so I've detrended, converted to % change, temporally smoothed, and averaged across runs [1]. Mostly I'm just trying to understand why this is happening.

Weirdly, I'm getting remarkably different R2 values from analyzePRF even when the timeseries correlation between the data and model look good. For example, here are two adjacent voxels:

![screenshot 2016-01-28 17 10 13](https://cloud.githubusercontent.com/assets/315810/12664271/3842b4d6-c5e3-11e5-9e9f-4b59c36e84ba.png)

(I've adapted your example 2 code to make this plot, here it is):

```matlab
% Define some variables
res = [101 101];                    % row x column resolution of the stimuli
resmx = 101;                        % maximum resolution (along any dimension)
hrf = results.options.hrf;          % HRF that was used in the model
degs = results.options.maxpolydeg;  % vector of maximum polynomial degrees used in the model

% Pre-compute cache for faster execution
[d,xx,yy] = makegaussian2d(resmx,2,2,2,2);

% Prepare the stimuli for use in the model
stimulusPP = {};
for p=1:length(imstack)
  stimulusPP{p} = squish(imstack{p},2)';  % this flattens the image so that the dimensionality is now frames x pixels
  stimulusPP{p} = [stimulusPP{p} p*ones(size(stimulusPP{p},1),1)];  % this adds a dummy column to indicate run breaks
end

% Define the model function.  This function takes parameters and stimuli as input and
% returns a predicted time-series as output.  Specifically, the variable <pp> is a vector
% of parameter values (1 x 5) and the variable <dd> is a matrix with the stimuli (frames x pixels).
modelfun = @(pp,dd) conv2run(posrect(pp(4)) * (dd*[vflatten(placematrix(zeros(res),makegaussian2d(resmx,pp(1),pp(2),abs(pp(3)),abs(pp(3)),xx,yy,0,0) / (2*pi*abs(pp(3))^2))); 0]) .^ posrect(pp(5)),hrf,dd(:,prod(res)+1));

% Construct projection matrices that fit and remove the polynomials.
% Note that a separate projection matrix is constructed for each run.
polymatrix = {};
for p=1:length(degs)
  polymatrix{p} = projectionmatrix(constructpolynomialmatrix(size(data{p},2),0:degs(p)));
end

voxels = [7857 5568]; % [good bad]
figure;
set(gcf,'Units','points','Position',[100 100 1000 200]);


for i=1:2

    vx = voxels(i);

    % For each run, collect the data and the model fit.  We project out polynomials
    % from both the data and the model fit.  This deals with the problem of
    % slow trends in the data.
    pp = results.params(1, :, vx);
    datats = polymatrix{1} * data{1}(vx,:)';
    modelts = polymatrix{1} * modelfun(pp,stimulusPP{1});

    % Visualize the results
    subplot(2, 1, i);
    hold on;
    plot(datats, 'r-');
    plot(modelts, 'b-');
    ylabel('BOLD signal');

    r2 = results.R2(vx);
    corrmat = corrcoef(datats, modelts);
    r = corrmat(1, 2);
    title(sprintf('Voxel %d | AnalyzePRF R2 = %.2f | timeseries correlation = %.2f', vx, r2, r));

    legend('data', 'model');

end

xlabel('Time (s)');
```

Does this set of results make sense to you? Do you have further ideas for how to debug?

[1] It's just occurred to me that the order of operations should probably be the other way around — average across runs then temporally smooth. But, no matter, I see the same thing when I don't temporally smooth.

**Comment by kendrickkay** [comment]
> I'm getting some confusing results when using analyzePRF; I'm hoping you can help me debug.
> 
> 
sure no problem


> As you can see, some aspects of it look right, but other aspects of it look like swiss cheese.
> 
> 
well, there are often large variations in contrast-to-noise across the brain (at least in my experience)...  there could be many causes...



> There's nothing apparently wrong in the mean maps,
> 
so, you have reasonable signal intensity in all of the places that look like holes?




> more directly to mrVista so I've detrended, converted to % change, temporally smoothed, and averaged across runs [1].
> 
i'm curious -- why temporally smoothed?  The pRF model in theory does something like temporal smoothing for you (the model prediction is after a convolution with a slow HRF timecourse).  One reason for temporal smoothing is that you are trying to avoid local minima (e.g. you don't want your model fitting to randomly converge on a high-temporal-frequency noise bump in your data).  maybe that's your reason?   (of course, one argument against temporal smoothing is that you might be worried that the high-frequency stuff is actually signal!!  (like a tiny tiny pRF))

> Weirdly, I'm getting remarkably different R2 values from analyzePRF even when the timeseries correlation between the data and model look good. For example, here are two adjacent voxels:
> 
>  <https://cloud.githubusercontent.com/assets/315810/12664271/3842b4d6-c5e3-11e5-9e9f-4b59c36e84ba.png>
> 

Hmm...  in the second voxel, the model is getting the gain wrong (the blue model fits are too high).  if you manually compute R2, does it come out to -4.08?

So, "typicalgain" is a parameter of analyzePRF and it is there because the optimizer can get confused and stuff. If you have data in raw signal units, 10 might be a reasonable value.  now that your data is in % BOLD change, something like 0.5 might be more reasonable.

maybe the optimizer is getting confused about fitting the gain parameter.  maybe if you give it a better initial seed, it'll be more happy (get to a better solution)

**Comment by mwaskom** [comment]
> well, there are often large variations in contrast-to-noise across the brain (at least in my experience)... there could be many causes...
> so, you have reasonable signal intensity in all of the places that look like holes?

Yep, there's dropout in the normal places, but it doesn't correspond in any way with the pattern of "holes" (nor do they appear to be consistently located on top of gyri or in sulci).

> i'm curious -- why temporally smoothed? 

Just trying to reproduce the statistic maps I have from when else analyzed these data using the normal mrVista pRF model. 

> Hmm...  in the second voxel, the model is getting the gain wrong (the blue model fits are too high).  if you manually compute R2, does it come out to -4.08?

I guess it depends on what you mean by manually compute R2. If you square the timeseries correlation, definitely not. I know that's not exactly how you're getting the model fit value, but it still seems strange to me that the model R2 can be so bad when just looking at the timeseries fits, it seems like it's doing alright.

Do you have example code for plotting the data and model fits across the different stimulus apertures, rather than across time?

> So, "typicalgain" is a parameter of analyzePRF and it is there because the optimizer can get confused and stuff. If you have data in raw signal units, 10 might be a reasonable value.  now that your data is in % BOLD change, something like 0.5 might be more reasonable.

> maybe the optimizer is getting confused about fitting the gain parameter.  maybe if you give it a better initial seed, it'll be more happy (get to a better solution)

I'm setting `typicalgain` to `1` (the only default fitting option I've changed). Indeed, changing this from 10 to 1 made a fairly large difference and shrunk a lot of the holes. So I think that's definitely part of it. I can try 0.5 tomorrow...

**Comment by kendrickkay** [comment]
> I guess it depends on what you mean by manually compute R2. If you square the timeseries correlation, definitely not. I know that's not exactly how you're getting the model fit value, but it still seems strange to me that the model R2 can be so bad when just looking at the timeseries fits, it seems like it's doing alright.
> 
> 

R2 = 100 * (1-sum(residuals.^2)/sum(data-mean(data)).^2)


> Do you have example code for plotting the data and model fits across the different stimulus apertures, rather than across time?
> 
> 
Not handy..


> So, "typicalgain" is a parameter of analyzePRF and it is there because the optimizer can get confused and stuff. If you have data in raw signal units, 10 might be a reasonable value. now that your data is in % BOLD change, something like 0.5 might be more reasonable.
> 
> maybe the optimizer is getting confused about fitting the gain parameter. maybe if you give it a better initial seed, it'll be more happy (get to a better solution)
> 
> I'm setting typicalgain to 1 (the only default fitting option I've changed). Indeed, changing this from 10 to 1 made a fairly large difference and shrunk a lot of the holes. So I think that's definitely part of it. I can try 0.5 tomorrow...
> 

In my experience, initial seed values that are exactly equal to 1 sometimes confuses MATLAB.  0.5 might be a better bet.

**Comment by mwaskom** [comment]
> R2 = 100 * (1-sum(residuals.^2)/sum(data-mean(data)).^2)

Is `data` a vector over time, or over stimulus apertures?

**Comment by kendrickkay** [comment]
Data is a time series....


% the percent variance in <y> that is explained by <x>.  this is achieved
% by calculating 100*(1 - sum((y-x).^2) / sum((y-mean(y).^2))).

**Comment by mwaskom** [comment]
> In my experience, initial seed values that are exactly equal to 1 sometimes confuses MATLAB.  0.5 might be a better bet.

OK, this does seem to make a pretty big difference.

I wouldn't say that makes sense, but things do look better now!

**Comment by mwaskom** [comment]
PS through further investigation I've determined that even lower values of `typicalgain` (~.15) yield very good results, eliminating the strong left skew in the distribution of R2 values and getting rid of "patchiness" in the surface maps.

Thanks for your help.

**Comment by kendrickkay** [comment]
Nice.  Maybe it's "easier" for the optimizer to grow the gain upwards to match the data as opposed to decreasing the gain downwards to match the data.

I'd be curious to see before and after screenshots of the surface maps if they're handy

**Comment by mwaskom** [comment]
Sure, e.g., here is the same subject/view as plotting in the first message in this issue thread:

![screenshot 2016-02-01 14 04 04](https://cloud.githubusercontent.com/assets/315810/12732931/befb85f0-c8ec-11e5-8ebf-655a38ad85a7.png)
