### ISSUE TITLE
parallel computing as a dependencies?

### ISSUE THREAD

**Issue by LaetitiaG** [kendrickkay/analyzePRF#10]
I was wondering whether the Matlab Parallel Computing Toolbox is mandatory to use analyzePRF, or if there is a way to not use it. If not, it may be useful to add it in the dependencies readme file.
Thanks a lot!

**Comment by kendrickkay** [comment]
Thanks.  I've updated the README with the following information:
========
Also, the code makes use of "parfor" (Matlab Parallel Computing Toolbox).
However, this is not mandatory, as you can change the "parfor" contained
in fitnonlinearmodel.m to a regular "for" loop, if you like.
