### ISSUE TITLE
training vs test performance

### ISSUE THREAD

**Issue by JWinawer** [kendrickkay/analyzePRF#7]
Hi Kendrick,

It looks like analyzePRF *might* by making a mistake by reporting training performance rather than test preformance when it runs in cross-validation mode. See line 573 in analyzePRF:
`  rA = a1.trainperformance;                                   % fits x voxels
`
Should it not be
`  rA = a1.testperformance;                                   % fits x voxels
`

@irisgroen
@KenYMB

Jon

**Comment by kendrickkay** [comment]
Yikes. I took a look and it appears you are right.  Before I fix it, are there any other larger issues that you are thinking about?  Hopefully this didn't cause any problems for you.  I don't think I ever use this mode (yet) so I wasn't affected

**Comment by JWinawer** [comment]
Ah. No other issues I know of. Do you know if we used this feature for the
HCP paper?

Anyway, good catch by @kenymb, who noticed it.

Jon

On Wed, Mar 4, 2020 at 4:32 PM Kendrick Kay <notifications@github.com>
wrote:

> Yikes. I took a look and it appears you are right. Before I fix it, are
> there any other larger issues that you are thinking about? Hopefully this
> didn't cause any problems for you. I don't think I ever use this mode (yet)
> so I wasn't affected
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kendrickkay_analyzePRF_issues_7-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAAQFPXSVXHIZ4HZYEXT7LS3RF3CG5A5CNFSM4LBUUVJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEN2NOJY-23issuecomment-2D594859815&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=O6DpXwqBdwAlsLjHkCsQFSX0ohBc0CBsV5OUphQpZBE&s=kAZocI1DKZj5GjY6g1WmG-UwHfpwbShvEe9ZL6iHQoo&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAQFPXTG3J3JLV3A6S3W6IDRF3CG5ANCNFSM4LBUUVJQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=O6DpXwqBdwAlsLjHkCsQFSX0ohBc0CBsV5OUphQpZBE&s=IBhsIblgO7aj1pRfihaIxvblVXh-KkcWBzVtWWaOFhg&e=>
> .
>


-- 
Jonathan Winawer
Associate Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by KenYMB** [comment]
Hi Kendrick,

In my case, output all of trainperformance, testperformance, and aggregatedtestperformance would be helpful.

Thank you,
Ken

**Comment by kendrickkay** [comment]
I did check, and no, the HCP paper didn't use this mechanism. (This is because separate calls were made to the full fit, and the two half fits).

I've added the extra fields and updated the documentation.  Sorry for the bug!
