### ISSUE TITLE
cross-validation mode update bug

### ISSUE THREAD

**Issue by MarcHimmelberg** [kendrickkay/analyzePRF#8]
Hi Kendrick,

I am running the recently updated version of analyzePRF with the cross-validation mode changes. The new version is giving me the error 'undefined function or variable xvalmode'. It looks like this is just because the recent changes on lines 599, 617, and 631 should be looking for 'options.xvalmode' rather than 'xvalmode'. Thanks!

Best,
Marc

**Comment by kendrickkay** [comment]
Whoops.  So sorry.  I should test code before commiting it.  I commited the fix.  Thanks for the headsup.
