### ISSUE TITLE
opt vs options in analyzePRF

### ISSUE THREAD

**Issue by JWinawer** [kendrickkay/analyzePRF#9]
Hi Kendrick,

It looks like in the function analyzePRF, lines 264-266, there are three instances of the variable "opt" that should probably be "options" instead. This is for running analyzePRF with "wantquick", which we do for some testing purposes. @kenyymb found this.

Jon

**Comment by JWinawer** [comment]
It looks like in the function analyzePRF, lines 264-266, there are three instances of the variable "opt" that should probably be "options" instead. This is for running analyzePRF with "wantquick", which we do for some testing purposes. @kenymb found this.

**Comment by kendrickkay** [comment]
Whoops, thanks for the heads up. it is fixed now.     Also, while I have your attention, I have been investigating further tweaks and optimiziations to annoying local minima issues if you are curious to hear more about.
